Updating Contract - Events committee
near/devgigsboard pull request #143
Opened 2024-07-18 21:46 UTC by Tguntenaar

The events-committee contract is out of date with all the latest changes made to `devhub.near`. 

The front-end is now on the `main` branch in the neardevhub-bos repo but doesn't deploy automatically because the vars/secret is not added to the devhub.near github action environment yet.

In order to update the events-committee.near we need to update both front end and back end together to avoid breaking changes.

2024-07-19 20:22 UTC, frol requested changes

2024-07-19 20:22 UTC, frol commented on src/access_control/members.rs
> +            Member::Account("events-committee.near".parse().unwrap()),
Do we need this change?

2024-07-19 20:22 UTC, frol commented on src/proposal/mod.rs
> +        String::from("Travel expenses"),
I think there is no sane defaults anymore, so I would drop the whole function completely.

2024-07-19 20:22 UTC, frol commented on src/proposal/repost.rs
> +        format!("/events-committee.near/widget/app?page=proposal&id={}", proposal.id);
It sounds like we should use `near_sdk::env::current_account_id()` here

2024-07-19 20:22 UTC, frol commented on tests/proposals.rs
> +                "category": "Bounty",
I would not change these. Instead, I would explicitly initialize the categories, so we don't need to rely on default categories list

2024-07-20 12:38 UTC, Tguntenaar commented
@frol this PR isn't supposed to merge into the main branch. These are just the changes I made to quickly deploy the events-committee contract. I should have made an issue instead, so I will close it.

2024-07-20 12:38 UTC, closed without merging