feat: added blog url and campaign / social short link tracking
near/devgigsboard pull request #145
Opened 2024-08-20 01:58 UTC by Tguntenaar

WIP

This PR does two things:
- Adds match pattern for the blog links (blogv2)
- Adds mapping for query parameters that track campaign and social for Joe

We want links like this: `/blog/dev-dao/blog-title?c=1&s=i` to work. Mapping is defined in [this spreadsheet](https://docs.google.com/spreadsheets/d/1q13ucr98W87Tlfq0AuUzY_GdDg9-2e3AddwhH4DpMIE/edit?pli=1&gid=0#gid=0)

2024-08-22 21:25 UTC, frol requested changes
It is not flexible to maintain the list of campaigns inside the contract. Just parse out all the query arguments from the URL (`?<query_args>`) and append them to the constructed redirect URL (`&<query_args>`)

2024-09-03 00:25 UTC, Tguntenaar commented
@frol could you review it one more time?

2024-09-04 07:51 UTC, frol commented on src/web4/handler.rs
> +        // let params: Vec<(&str, &str)> = parameters
Do we need this dead commented out code?

2024-09-04 07:51 UTC, frol commented on src/web4/handler.rs
> +                &current_account_id, community, blog_title
Have you tested it with titles that have spaces, question marks, ampersands, and slashes? Please, add tests for these cases

2024-09-04 07:51 UTC, frol commented on src/web4/handler.rs
> +            let blog_title = last.split('?').next().unwrap();
I would consider simply requiring that the blog title is separated away with /, so the split(/).get(3) will just give you the title. Here is an example URL: `/blog/devdao/Here+is+the+title/?…` (note the / before ?)

2024-10-10 17:46 UTC, Tguntenaar commented
@race-of-sloths include

2024-10-25 18:04 UTC, race-of-sloths commented
@Tguntenaar Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!
Weekly streak is on the road, smart strategy! Secure your streak with another PR!

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://race-of-sloths.com/images/bot-banner-dark.svg">
    <source media="(prefers-color-scheme: light)" srcset="https://race-of-sloths.com/images/bot-banner-light.svg">
    <img alt="Shows inviting banner with latest news." src="https://race-of-sloths.com/images/bot-banner-light.svg">
</picture>](https://race-of-sloths.com/latest-news)

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/Tguntenaar?type=bot&pr=NEAR-DevHub/neardevhub-contract/145&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/Tguntenaar?type=bot&pr=NEAR-DevHub/neardevhub-contract/145&theme=light">
    <img alt="Shows profile picture for the author of the PR" src="https://badge.race-of-sloths.com/Tguntenaar?type=bot&pr=NEAR-DevHub/neardevhub-contract/145&theme=white">
</picture>](https://race-of-sloths.com/profile/Tguntenaar)


<details><summary>Current status: <i>stale</i></summary>

This pull request was removed from the race, but you can include it again with `@race-of-sloths include` command
</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/Tguntenaar)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Invite contributor** `@race-of-sloths invite` to invite the contributor to participate in a race or include it, if it's already a runner.
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

2025-02-26 12:47 UTC, closed without merging